// Generated by CoffeeScript 1.4.0
var loadingMask;

loadingMask = {
  delay: 100,
  spinner: {},
  opts: {
    color: '#bd0d00',
    shape: 'spiral',
    diameter: 150,
    density: 100,
    range: 1.4,
    FPS: 50
  },
  createSpinner: function() {
    if (_.isEmpty(this.spinner)) {
      this.spinner = new CanvasLoader("search_res_div");
      this.spinner.setShape(this.opts.shape);
      this.spinner.setColor(this.opts.color);
      this.spinner.setDiameter(this.opts.diameter);
      this.spinner.setDensity(this.opts.density);
      this.spinner.setRange(this.opts.range);
      return this.spinner.setFPS(this.opts.FPS);
    }
  },
  show: function(spinner) {
    if (spinner == null) {
      spinner = true;
    }
    this.createSpinner();
    if (spinner) {
      return this.spinner.show();
    }
  },
  hide: function() {
    return this.spinner.hide();
  }
};
