// Generated by CoffeeScript 1.4.0

!(function(d, s, id) {
  var fjs, js;
  js = void 0;
  fjs = d.getElementsByTagName(s)[0];
  if (!d.getElementById(id)) {
    js = d.createElement(s);
    js.id = id;
    js.src = "https://platform.twitter.com/widgets.js";
    return fjs.parentNode.insertBefore(js, fjs);
  }
})(document, "script", "twitter-wjs");

(function(d, s, id) {
  var fjs, js;
  js = void 0;
  fjs = d.getElementsByTagName(s)[0];
  if (d.getElementById(id)) {
    return;
  }
  js = d.createElement(s);
  js.id = id;
  js.src = "//connect.facebook.net/en_US/all.js#xfbml=1&appId=134627846735967";
  return fjs.parentNode.insertBefore(js, fjs);
})(document, "script", "facebook-jssdk");
