// Generated by CoffeeScript 1.4.0
var index;

index = {
  template: JST["map/info"],
  init: function() {
    this.detect_elements();
    return this.bind_events();
  },
  detect_elements: function() {
    this.gmap_input = $("#gmaps-input-address");
    this.gmap_error = $("#gmaps-error");
    this.jmap = $("#gmaps-canvas");
    this.map_options = {
      zoom: 13,
      maxZoom: 18,
      minZoom: 3,
      center: new google.maps.LatLng(40.752508, -73.993714),
      mapTypeId: google.maps.MapTypeId.ROADMAP
    };
    this.map_d = void 0;
    this.map_a = void 0;
    this.markers_d = [];
    this.markers_a = [];
    this.image = new google.maps.MarkerImage("../img/marker-images/image.gif", new google.maps.Size(18, 17), new google.maps.Point(0, 0), new google.maps.Point(9, 17));
    this.shadow = new google.maps.MarkerImage("../img/marker-images/shadow.png", new google.maps.Size(30, 17), new google.maps.Point(0, 0), new google.maps.Point(9, 17));
    this.shape = {
      coord: [10, 0, 11, 1, 12, 2, 13, 3, 14, 4, 15, 5, 16, 6, 17, 7, 14, 8, 15, 9, 15, 10, 15, 11, 15, 12, 15, 13, 15, 14, 15, 15, 14, 16, 3, 16, 2, 15, 2, 14, 2, 13, 2, 12, 2, 11, 2, 10, 2, 9, 3, 8, 0, 7, 1, 6, 2, 5, 3, 4, 4, 3, 3, 2, 3, 1, 3, 0, 10, 0],
      type: "poly"
    };
    this.map_name_d = "gmaps-canvas-depart";
    this.map_name_a = "gmaps-canvas-arrive";
    this.gmarkers = [];
    return this.companies = $("input:checkbox[name=companies]");
  },
  bind_events: function() {
    return this.initialize_map();
  },
  update_ui: function(address, latLng) {
    this.gmap_input.autocomplete("close");
    this.gmap_input.val(address);
    this.lat_input.val(latLng.lat());
    return this.lng_input.val(latLng.lng());
  },
  checkbox_click: function() {
    return this.companies.click(function() {
      index.clearOverlays();
      return index.get_markers();
    });
  },
  all_click: function() {
    var me;
    me = this;
    return $("input:checkbox[name=all]").click(function() {
      me.companies.removeAttr("checked");
      if ($(this).is(":checked")) {
        me.companies.attr("checked", "checked");
      }
      index.clearOverlays();
      return index.get_markers();
    });
  },
  clearOverlays: function() {
    var i;
    i = 0;
    while (i < this.markers_a.length) {
      this.markers_a[i].setMap(null);
      i++;
    }
    this.markers_a = [];
    i = 0;
    while (i < this.markers_d.length) {
      this.markers_d[i].setMap(null);
      i++;
    }
    return this.markers_d = [];
  },
  initialize_map: function() {
    var gmap;
    this.map_options.center = new google.maps.LatLng($("#d_lat").val(), $("#d_long").val());
    if ($("#d_lat").val() === "40") {
      this.map_options.zoom = 4;
    }
    gmap = document.getElementById(this.map_name_d);
    this.map_d = new google.maps.Map(gmap, this.map_options);
    this.map_options.center = new google.maps.LatLng($("#a_lat").val(), $("#a_long").val());
    gmap = document.getElementById(this.map_name_a);
    this.map_a = new google.maps.Map(gmap, this.map_options);
    this.get_markers();
    this.checkbox_click();
    this.all_click();
    return google.maps.visualRefresh = true;
  },
  get_markers: function() {
    var companies, me,
      _this = this;
    me = this;
    companies = [];
    $("input:checkbox[name=companies]:checked").each(function() {
      return companies.push($(this).val());
    });
    return $.ajax({
      url: SYS.baseUrl + 'map/get_markers',
      data: $.param({
        companies: companies
      }),
      type: 'POST',
      dataType: 'json',
      success: function(res) {
        if (res.text = "success") {
          return $.each(res.data, function(i, item) {
            var infowindow_a, infowindow_b, marker_a, marker_d;
            marker_a = new google.maps.Marker({
              position: new google.maps.LatLng(item.lat, item.long),
              map: me.map_a
            });
            infowindow_a = new google.maps.InfoWindow({
              content: ""
            });
            google.maps.event.addListener(marker_a, "click", function() {
              var _this = this;
              return $.ajax({
                url: SYS.baseUrl + 'map/get_info',
                data: $.param({
                  id: item.id
                }),
                type: 'POST',
                dataType: 'json',
                success: function(res) {
                  if (res.text = "success") {
                    infowindow_a.setContent(me.template({
                      item: res.data,
                      url: SYS.baseUrl
                    }));
                    return infowindow_a.open(me.map_a, marker_a);
                  }
                }
              });
            });
            marker_d = new google.maps.Marker({
              position: new google.maps.LatLng(item.lat, item.long),
              map: me.map_d
            });
            infowindow_b = new google.maps.InfoWindow({
              content: ""
            });
            google.maps.event.addListener(marker_d, "click", function() {
              var _this = this;
              return $.ajax({
                url: SYS.baseUrl + 'map/get_info',
                data: $.param({
                  id: item.id
                }),
                type: 'POST',
                dataType: 'json',
                success: function(res) {
                  if (res.text = "success") {
                    infowindow_b.setContent(me.template({
                      item: res.data,
                      url: SYS.baseUrl
                    }));
                    return infowindow_b.open(me.map_d, marker_d);
                  }
                }
              });
            });
            me.markers_a.push(marker_a);
            return me.markers_d.push(marker_d);
          });
        }
      }
    });
  }
};

$(document).ready(function() {
  return index.init();
});
