// Generated by CoffeeScript 1.4.0
var index;

index = {
  template: JST["home/table"],
  template_text: JST['home/text'],
  init: function() {
    this.detectElements();
    return this.bindEvents();
  },
  detectElements: function() {
    this.form = $('#schedule');
    this.search_res = $('#search_res_div');
    this.read_more = $('.read-more');
    this.info = $('.info-block');
    this.slider = $(".slider-range");
    this.inp_beg = $("#time_beg");
    this.inp_end = $("#time_end");
    this.span_beg = $(".time-beg");
    this.span_end = $(".time-end");
    this.options = {
      success: this.showResponse,
      beforeSend: function() {
        return loadingMask.show();
      }
    };
    return this.companies = $(".c_name");
  },
  bindEvents: function() {
    this.initFormSubmit();
    this.initTheme();
    this.company_click();
    return this.all_click();
  },
  range_slider_init: function() {
    var me;
    me = this;
    return this.slider.slider({
      range: true,
      min: 5,
      max: 1435,
      step: 5,
      values: [5, 1435],
      slide: function(e, ui) {
        var values;
        values = [];
        _.each(ui.values, function(num, key) {
          var hours, minutes;
          hours = Math.floor(num / 60);
          minutes = num - (hours * 60);
          return values.push(index.format_date(hours, minutes));
        });
        me.span_beg.html(values[0]);
        me.span_end.html(values[1]);
        me.inp_beg.val(values[0]);
        return me.inp_end.val(values[1]);
      }
    });
  },
  format_date: function(hours, minutes) {
    var ampm, strTime;
    ampm = (hours >= 12 ? "pm" : "am");
    hours = hours % 12;
    hours = (hours > 9 ? hours : "0" + hours);
    minutes = (minutes < 10 ? "0" + minutes : minutes);
    return strTime = hours + ":" + minutes + " " + ampm;
  },
  all_click: function() {
    var me;
    me = this;
    return $("input:checkbox[name=all]").click(function() {
      me.companies.removeAttr("checked");
      if ($(this).is(":checked")) {
        return me.companies.attr("checked", "checked");
      }
    });
  },
  company_click: function() {
    this.read_more.popover();
    return this.read_more.click(function(e) {
      var element;
      element = this;
      index.read_more.each(function() {
        if (this !== element) {
          $(this).popover('hide');
          return $(".infor").remove();
        }
      });
      if ($(".infor").length <= 0) {
        $(".popover-content").append('<a class="infor" href="' + SYS.baseUrl + 'company/info/' + $(element).data('title') + '">Read More</a>');
      }
      return e.preventDefault();
    });
  },
  initTheme: function() {
    return $.extend($.tablesorter.themes.bootstrap, {
      table: "table table-striped",
      header: "bootstrap-header",
      footerRow: "",
      footerCells: "",
      icons: "",
      sortNone: "bootstrap-icon-unsorted",
      sortAsc: "icon-chevron-up",
      sortDesc: "icon-chevron-down",
      active: "",
      hover: "",
      filterRow: "",
      even: "",
      odd: ""
    });
  },
  showResponse: function(responseText, statusText, xhr, $form) {
    var obj;
    loadingMask.hide();
    obj = jQuery.parseJSON(responseText);
    if (obj.text === "success") {
      index.search_res.empty();
      index.search_res.append(index.template({
        schedules: obj.data,
        baseurl: SYS.baseUrl
      }));
      return index.initTable();
    } else {
      index.search_res.empty();
      return index.search_res.append(index.template_text({
        text: obj.errors
      }));
    }
  },
  initTable: function() {
    return $("table").tablesorter({
      theme: "bootstrap",
      widthFixed: true,
      headerTemplate: "{content} {icon}",
      widgets: ["uitheme", "zebra"],
      widgetOptions: {
        zebra: ["even", "odd"]
      },
      headers: {
        5: {
          sorter: false
        },
        6: {
          sorter: false
        }
      }
    });
  },
  initFormSubmit: function() {
    var _this = this;
    return this.form.submit(function(e) {
      var el;
      el = $(e.currentTarget);
      _this.search_res.empty();
      el.ajaxSubmit(_this.options);
      return false;
    });
  }
};

$(document).ready(function() {
  return index.init();
});
