// Generated by CoffeeScript 1.4.0
var raty;

$(function() {
  $(window).scroll(function() {
    if ($(this).scrollTop() !== 0) {
      return $("#toTop").fadeIn();
    } else {
      return $("#toTop").fadeOut();
    }
  });
  return $("#toTop").click(function() {
    return $("body,html").animate({
      scrollTop: 0
    }, 800);
  });
});

raty = {
  init: function() {
    this.detect_elements();
    return this.bind_events();
  },
  detect_elements: function() {
    this.timeliness = $("#timeliness");
    this.comfort = $("#comfort");
    this.wifi = $("#wifi");
    this.empty_seating = $("#empty-seating");
    return this.cleanliness = $("#cleanliness");
  },
  bind_events: function() {
    return this.create_rate();
  },
  create_rate: function() {
    this.timeliness.raty({
      half: true,
      size: 24,
      starHalf: SYS.baseUrl + "img/stars/star-half-big.png",
      starOff: SYS.baseUrl + "img/stars/star-off-big.png",
      starOn: SYS.baseUrl + "img/stars/star-on-big.png",
      score: 5,
      target: '#timeliness-input',
      targetType: 'number',
      targetKeep: true
    });
    this.comfort.raty({
      half: true,
      size: 24,
      starHalf: SYS.baseUrl + "img/stars/star-half-big.png",
      starOff: SYS.baseUrl + "img/stars/star-off-big.png",
      starOn: SYS.baseUrl + "img/stars/star-on-big.png",
      score: 5,
      target: '#comfort-input',
      targetType: 'number'
    });
    this.wifi.raty({
      half: true,
      size: 24,
      starHalf: SYS.baseUrl + "img/stars/star-half-big.png",
      starOff: SYS.baseUrl + "img/stars/star-off-big.png",
      starOn: SYS.baseUrl + "img/stars/star-on-big.png",
      score: 5,
      target: '#wifi-input',
      targetType: 'number'
    });
    this.empty_seating.raty({
      half: true,
      size: 24,
      starHalf: SYS.baseUrl + "img/stars/star-half-big.png",
      starOff: SYS.baseUrl + "img/stars/star-off-big.png",
      starOn: SYS.baseUrl + "img/stars/star-on-big.png",
      score: 5,
      target: '#empty-seating-input',
      targetType: 'number'
    });
    return this.cleanliness.raty({
      half: true,
      size: 24,
      starHalf: SYS.baseUrl + "img/stars/star-half-big.png",
      starOff: SYS.baseUrl + "img/stars/star-off-big.png",
      starOn: SYS.baseUrl + "img/stars/star-on-big.png",
      score: 5,
      target: '#cleanliness-input',
      targetType: 'number'
    });
  }
};

$(document).ready(function() {
  return raty.init();
});
